### ISSUE TITLE
 make osx1010-desktop hangs after DMG creation

### ISSUE THREAD

**Issue by scottelundgren** [box-cutter/osx-vm#5]
Using VMware Fusion Professional 7.10 (2314774). Selecting 'Boot normally' in the VMware Boot manager (first screenshot) seems to start goes to second screenshot then goes back to first screenshot.
![screen shot 2015-02-04 at 11 33 19 am](https://cloud.githubusercontent.com/assets/664278/6044654/c1ac5448-ac62-11e4-948d-6cfb6a432774.png)
![screen shot 2015-02-04 at 11 33 34 am](https://cloud.githubusercontent.com/assets/664278/6044655/c1b75366-ac62-11e4-9432-c7862ce38cb3.png)

command line output is
```
Warnings for build 'vmware-iso':

* A checksum type of 'none' was specified. Since ISO files are so big,
a checksum is highly recommended.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: file:///dmg/OSX_InstallESD_10.10_14A389.dmg
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting virtual machine...
==> vmware-iso: Waiting 2s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for SSH to become available...
```

**Comment by annawake** [comment]
It's usually a sign that you're not pointing at the correct boot ISO image.  Double-check that the filenames match from what you generated, and that the dmg is generated correctly.  It appears that it is looking for the file in /dmg//OSX_InstallESD_10.10_14A389.dmg - which doesn't look like it would be correct.
